# Generated by Django 4.2.17 on 2025-01-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
