# Generated by Django 4.2.17 on 2025-01-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='status',
            field=models.IntegerField(choices=[(0, 'At Large!'), (1, 'Caught!')], default=0),
        ),
    ]
