# Generated by Django 4.2.17 on 2025-01-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_wanted_pirate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='bounty',
            field=models.BigIntegerField(),
        ),
    ]
