# Generated by Django 4.2.17 on 2025-01-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_wanted_bounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
