# Generated by Django 4.2.17 on 2025-01-15 21:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_alter_wanted_created_on_alter_wanted_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='pirate_image',
            field=cloudinary.models.CloudinaryField(default='images/marines_aculb0.png', max_length=255, verbose_name='image'),
        ),
    ]
