# Generated by Django 4.2.17 on 2025-01-15 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_alter_wanted_bounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='bounty',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
